- hosts: localhost
  pre_tasks:
    - name: Update Homebrew
      command: brew update
      tags:
        - core

  tasks:
    - name: Set up dotfiles
      import_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
        - core
    
    - name: Set up development environment
      import_tasks: tasks/development.yml
      tags:
        - dev
        - core
    
    - name: Set up Node
      import_tasks: tasks/node.yml
      tags:
        - node
        - core
    
    - name: Set up Python
      import_tasks: tasks/python.yml
      tags:
        - python
        - core

    - name: Set up Core Productivity
      import_tasks: tasks/core-productivity.yml
      tags:
        - productivity
        - core

    - name: Set up Personal Productivity
      import_tasks: tasks/personal-productivity.yml
      tags:
        - productivity
        - personal

    