- name: Create dev directory
  file:
    path: "{{ lookup('env', 'HOME') }}/dev"
    state: directory
    mode: '0755'

- name: Install Alacritty
  package:
    name: alacritty
    state: present
  tags:
    - alacritty
    - terminal

- name: Install tmux
  package:
    name: tmux
    state: present
  tags:
    - clitools
    - terminal

- name: Cloning tpm
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm/"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: Install fzf
  package:
    name: fzf
    state: present
  tags:
    - clitools
    - terminal

- name: Install ripgrep 
  package:
    name: ripgrep
    state: present
  tags:
    - clitools
    - terminal

- name: Install fd
  package:
    name: fd
    state: present
  tags:
    - clitools

- name: Install neovim
  package:
    name: neovim
    state: present
  tags:
    - neovim
    - vim
    - editor

- name: Install Go
  package:
    name: go
    state: present
  tags:
    - go

- name: Install VS Code
  package:
    name: visual-studio-code
    state: present
  tags:
    - vscode
    - editor

- name: Install Docker
  package:
    name: docker
    state: present
  tags:
    - docker

- name: Tap Font Cask
  command: brew tap homebrew/cask-fonts
  tags: 
    - font
  
- name: Install Jet Brains Nerd Font
  command: brew install --cask font-jetbrains-mono-nerd-font
  tags: 
    - font
  
