- name: Installing stow
  package: 
    name: stow
    state: present
        
- name: Cloning .dotfiles
  git:
    repo: 'git@github.com:alexguillamon/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: Create .zshrc
  file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles/zsh/.zshrc"
    state: touch

- name: Ensure the install script is executable
  file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles/install"
    mode: '0755'

- name: Stow dotfiles
  shell: "{{ lookup('env', 'HOME') }}/.dotfiles/install"
  args:
    executable: /bin/zsh

- name: Setup Zi
  shell: "source <(curl -sL init.zshell.dev); zzinit"
  args:
    executable: /bin/zsh

- name: Install subversion
  package:
    name: subversion
    state: present

- name: Add .zshrc_core to .zshrc
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: "source {{ lookup('env', 'HOME') }}/.zshrc_core"
    create: yes
    insertafter: EOF
