- name: Installing stow
  package: 
    name: stow
    state: present
        
- name: Cloning .dotfiles
  git:
    repo: 'git@github.com:alexguillamon/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: Copy .zshrc file from template
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/ansible/template/.zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
  tags:
    - dotfiles

- name: Remove .zprofile file
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.zprofile"
    state: absent
  tags:
    - dotfiles

- name: Ensure the install script is executable
  file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles/install"
    mode: '0755'

- name: Stow dotfiles
  shell: "{{ lookup('env', 'HOME') }}/.dotfiles/install"
  args:
    executable: /bin/zsh

- name: Setup Zi
  shell: "source <(curl -sL init.zshell.dev); zzinit"
  args:
    executable: /bin/zsh

- name: Install subversion
  package:
    name: subversion
    state: present
