- name: Install fnm
  shell: "curl -fsSL https://fnm.vercel.app/install | bash"
  args:
    executable: /bin/zsh

- name: Install Node.js
  shell: "fnm install --lts"
  args:
    executable: /bin/zsh

- name: Set default Node.js version
  shell: "fnm default lts-latest"
  args:
    executable: /bin/zsh

- name: Load fnm
  shell: "exec zsh"
  args:
    executable: /bin/zsh

- name: Install PNPM 
  shell: "npm install -g pnpm"
  args:
    executable: /bin/zsh

- name: Install eslint
  npm:
    name: eslint
    global: yes

- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: yes

- name: Install Typescript
  npm:
    name: typescript
    global: yes
  
- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
 
