- name: Install fnm
  ansible.builtin.shell: "curl -fsSL https://fnm.vercel.app/install | bash"
  args:
    executable: /bin/zsh

- name: Install Node.js
  ansible.builtin.shell: "fnm install --lts"
  args:
    executable: /bin/zsh

- name: Set default Node.js version
  ansible.builtin.shell: "fnm default lts"
  args:
    executable: /bin/zsh

- name: Install PNPM 
  ansible.builtin.shell: "npm install -g pnpm"
  args:
    executable: /bin/zsh