- name: Install dropbox
  homebrew_cask:
    name: dropbox
    state: latest

- name: Install notion
  homebrew_cask:
    name: notion
    state: latest

- name: Install nordvpn
  homebrew_cask:
    name: nordvpn
    state: latest
